account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from .forms import (UserLoginForm)
from django.views.generic import TemplateView
from .forms import  UserLoginForm
from . import views





app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/registration/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),                                            
    path('register/', views.account_register, name='register'),
    path('dashboard/', views.user_orders, name='dashboard'),
    path("add_address/", views.add_address, name="add_address"),
    path("addresses/", views.view_address, name="addresses"),
    # path("user_orders/", views.user_orders, name="user_orders"),
  
    
]

checkout/urls.py
from django.urls import include, path

from . import views

app_name = "checkout"

urlpatterns = [
    path("delivery_address/", views.delivery_address, name="delivery_address"),
    path("payment_selection/", views.payment_selection, name="payment_selection"),
    path("payment_complete/", views.payment_complete, name="payment_complete"),
    # path("payment_successful/", views.payment_successful, name="payment_successful"),
]

djangoProject3/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
     path('', include('store.urls', namespace='store')),
     path('basket/', include('basket.urls', namespace='basket')),
     path('account/', include('account.urls', namespace='account')),
     path('checkout/', include('checkout.urls', namespace='checkout')),
     path("orders/", include("orders.urls", namespace="orders")),
     
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_all, name='product_all'),
    path('item/<slug:slug>/', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
]

checkout/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

class PaymentSelections(models.Model):
    """
    Store payment options
    """

    name = models.CharField(
        verbose_name=_("name"),
        help_text=_("Required"),
        max_length=255,
    )

    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = _("Payment Selection")
        verbose_name_plural = _("Payment Selections")

    def __str__(self):
        return self.name

checkout/views.py
import json

from account.models import Address
from basket.basket import Basket
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from orders.models import Order, OrderItem

@login_required
def delivery_address(request):
    addresses = Address.objects.filter(customer=request.user).order_by("-default")
    return render(request, "checkout/delivery_address.html",{"addresses":addresses})


@login_required
def payment_selection(request):
    session = request.session
    return render(request, "checkout/payment_selection.html", {})


####
# PayPay
####
from paypalcheckoutsdk.orders import OrdersGetRequest

from .paypal import PayPalClient


@login_required
def payment_complete(request):
    PPClient = PayPalClient()

    body = json.loads(request.body)
    data = body["orderID"]
    user_id = request.user.id

    requestorder = OrdersGetRequest(data)
    response = PPClient.client.execute(requestorder)

    total_paid = response.result.purchase_units[0].amount.value

    basket = Basket(request)
    order = Order.objects.create(
        user_id=user_id,
        full_name=response.result.purchase_units[0].shipping.name.full_name,
        email=response.result.payer.email_address,
        address1=response.result.purchase_units[0].shipping.address.address_line_1,
        postal_code=response.result.purchase_units[0].shipping.address.postal_code,
        total_paid=response.result.purchase_units[0].amount.value,
        order_key=response.result.id,
        payment_option="paypal",
        billing_status=True,
    )
    order_id = order.pk

    for item in basket:
        OrderItem.objects.create(order_id=order_id, product=item["product"], price=item["price"], quantity=item["qty"])

    return JsonResponse("Payment completed!", safe=False)


@login_required
def payment_successful(request):
    basket = Basket(request)
    basket.clear()
    return render(request, "checkout/payment_successful.html", {})

templates/checkout/add_address_form.html
{% extends "../store/base.html" %}
{% load static %}
{% block title %}Basket Summary{%endblock %}
{% block content %}
  <div class="col-6 mx-auto">
    <h1 class="h3">Add Address</h1>
    <div>Add a new delivery <b>address</b></div>
    <hr />
    <form name="address_form" class="account-form" method="post" enctype="multipart/form-data">
      {% if form.errors %}
      <div class="alert alert-primary" role="alert">
        Error: Please try again!
      </div>
      {% endif %}
      {% csrf_token %}
      <label class="small fw-bold">{{ form.full_name.label}}</label>
      {{ form.full_name }}
      <label class="small fw-bold">{{ form.phone.label}}</label>
      {{ form.phone }}
      <label class="small fw-bold">{{ form.address_line.label}}</label>
      {{ form.address_line }}
      <label class="small fw-bold">{{ form.town_city.label}}</label>
      {{ form.town_city }}
      <label class="small fw-bold">{{ form.postcode.label}}</label>
      {{ form.postcode }}
      <button class="btn btn-primary btn-block py-2 mb-4 mt-4 fw-bold w-100" type="button" value="Submit" onclick="submitForm()">
      Add Address
      </button>
    </form>
  
  </div>
  


  <script> 
  function submitForm() {
     var form = document.getElementsByName('address_form')[0];
     form.submit(); // Submit the form
     form.reset();  // Reset all form data
     return false; // Prevent page refresh
  }
  </script>
  {% endblock %}

templates/checkout/delivery_address.html
{% extends "../store/base.html" %}
{% load static %}
{% block title %}Basket Summary{%endblock %}
{% block content %}

<div class="container">
  <div class="col-12">
    <h1 class="h2">Addresses</h1>
  </div>
  
  <hr />
</div>


<div class="container">
  <div class="row g-3">
    <div class="col-md-4 col-lg-4 order-md-last p-0 order-3">
    
<div class="d-flex bd-highlight">
  <div class="p-2 flex-grow-1 bd-highlight">Total:</div>
  <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="total"class="fw-bold h5">{{basket.get_total_price}}</span></div>
</div>
<a role="button" href="{%url "checkout:payment_selection"%}" class="btn btn-success fw-bold w-100" type="button">Pay Securely</a>
</div>
    
    <div class="col-md-7 col-lg-8">
      {% for address in addresses %}
      {% if not address.default %}
        <h1 class="h5 pt-4">Other Addresses</h1>
      {% endif %}
      <div class="card mb-3 border-1 rounded-0 product-item me-md-4" data-index="{{option.id}}">
        <div class="row g-0">
          <div class="col">
            <div class="card pb-3 rounded-0">
              <div class="card-header bg-white small text-muted">
                {% if address.default %}
                Selected
                {% endif %}
                &nbsp;
              </div>
              <div class="card-body small pb-1">
                <p class="card-text m-0 fw-bold">{{address.full_name}}</p>
                <p class="card-text m-0">{{address.address_line}}</p>
                <p class="card-text m-0">{{address.address_line2}}</p>
                <p class="card-text m-0">{{address.town_city}}</p>
                <p class="card-text m-0">{{address.postcode}}</p>
                <p class="card-text m-0">Phone number: {{address.phone}}</p>
                <div class="pt-5">
                  
                </div>
              </div>
            </div>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>

  <h1 class="h2"> Add your Address</h1>
  <div>Manage your <b>addresses</b> and delivery preferences</div>
  <hr />
  <div class="container px-0">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <div class="col">
        <a href="{% url "account:add_address" %}" class="text-reset text-decoration-none" role="button"
          style="max-width: 540px;">
          <div class="card mb-3 h-100" style="border: dashed 2px #ccc;">
            <div class="row g-0 h-100">
              <div class="col-12" style="min-height:100px">
                <div class="card-body text-center position-absolute top-50 start-50 translate-middle">
                  <svg style="color:#ccc;" xmlns="http://www.w3.org/2000/svg" width="60" height="60" fill="currentColor"
                    class="bi bi-plus" viewBox="0 0 16 16">
                    <path
                      d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
                  </svg>
                  <h1 class="h5">Add Address</h1>
                </div>
              </div>
            </div>
          </div>
        </a>
      </div>
  {% endblock %}

templates/checkout/payment_selection.html
{% extends "../store/base.html" %}
{% load static %}
{% block title %}Basket Summary{%endblock %}
{% block content %}
<div class="container">
    <div class="col-12">
      <h1 class="h2">Payment</h1>
    </div>
    <hr />
  </div>
  
  <div class="container">
    <div class="row g-3">
      <div class="col-md-4 col-lg-4 order-md-last p-0 order-3">
        <div class="d-flex bd-highlight">
          <div class="p-2 flex-grow-1 bd-highlight">Total:</div>
          <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="total"
              class="fw-bold h5">{{basket.get_total_price}}</span></div>
        </div>
      </div>
      <div class="col-md-7 col-lg-8 pe-0 pe-md-5">
        <div id="paypal-button-container"></div>
      </div>
    </div>
  </div>

  <script
  src="https://www.paypal.com/sdk/js?client-id=AUOOir3F1mGhB-v6M9rnS_eWqWSmNqcxiUTGBj7l-vx_D97P8oDvvsxnEqVHDixbRGzflLBSCX81VdYr&currency=USD"
  data-sdk-integration-source="button-factory">
</script>

<script>
    function getCookie(name) {
      var cookieValue = null;
      if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
          var cookie = cookies[i].trim();
          if (cookie.substring(0, name.length + 1) === (name + '=')) {
            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
            break;
          }
        }
      }
      return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');
  
    function initPayPalButton() {
      paypal.Buttons({
        style: {
          shape: 'rect',
          color: 'gold',
          layout: 'vertical',
          label: 'paypal',
  
        },
      createOrder: function (data, actions) {
          return actions.order.create({
            purchase_units: [{
              "amount": {
                "currency_code": "USD",
                "value": '{{basket.get_total_price}}'
              }
            }]
          });
        },
      onApprove: function (data) {
        
          return fetch(url, {
            method: 'POST',
            headers: {
              'content-type': 'application/json',
              'X-CSRFToken': csrftoken,
            },
            body: JSON.stringify({
              orderID: data.orderID
            })
          }).then(function () {
            {% comment %} location.href = '{% url 'checkout:payment_successful' %}'; {% endcomment %}
          })
        },
      }).render('#paypal-button-container');
    }
    initPayPalButton();
  
      </script>
{%endblock%}

templates/checkout/payment_successful.html
{% extends "../base.html" %}
{% load static %}
{% block title %}Payment Successful{%endblock %}
{% block content %}

<div class="container">
  <div class="col-12">
    <h1 class="h2">Payment Successful</h1>
  </div>
  <div class="col-12">
    <p>Order Summary</p>
  </div>
  <hr />
  <div class="col-12">
    <p>View all <a href="{% url 'account:dashboard'%}">orders</a></p>
  </div>
</div>


{% endblock %}